name = "Gruvhugo"
license = "GPL-3.0"
licenselink = "https://gitlab.com/avron/gruvhugo/-/blob/master/LICENSE"
description = "A minmal theme based on the Gruvbox color scheme."
demosite = "https://avron.gitlab.io/gruvhugo/"
homepage = "https://avron.gitlab.io/gruvhugo/"
tags = ["landing page", "gruvbox", "blog", "mobile", "light", "minimal", "modern", "customizable", "dark mode"]
features = ["fast", "dark mode", "Responsive", "Clean", "Simple"]
min_version = "0.41"

[author]
  name = "Abraham Raji"
  homepage = "https://abrahamraji.in"


baseURL = ''




# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "fast, hugo, theme, minimal, gruvbox"
  headerTitle = "Lesly Bautista"
  copyright = "© 2023 Lesly Bautista.  <a href=\"https://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>."
  name = "jane_doe"
  img = "./img/author.jpeg"
  img_title = "Thanks to Christina @ wocintechchat.com for this photo."
  icon = "img/logo.png"
  quote = "I dream my painting, and then I paint my dream - Van Gogh"
  description= "My name is Lesly Bautista, and I graduated from Universidad Nacional Mayor de San Marcos with a degree in geographic engineering. I come from Peru, a country with incredible geographical diversity, and I've always been fascinated by maps' ability to reveal the complexities of our world. This passion has led me to collaborate with prestigious organizations such as the Peruvian Space Agency and the United Nations Development Programme on projects in geovisualization, geospatial database management, and spatial analysis in a variety of settings, from urban to rural."
  licenseUrl = ""

 # Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/avron/gruvhugo"

  [[params.social]]
    name = "email"
    url  = "mailto:leslyarcelly.213@gmail.com"

  [[params.social]]
    name = "gpg"
    url  = "https://keys.openpgp.org/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/leslybautista"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

[params.style]
  # add path to custom CSS files here
  custom_css = []
  # add path to custom SCSS files here
  custom_scss = []

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "post/"

  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "https://leslybautista.github.io/CV/"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
